[package]
name = "nlp"
version = "0.1.0"
authors = ["Supratik Chatterjee <supratikdevm96@gmail.com>"]
edition = "2018"

[dependencies]

literal = {path = "./literal"}
sentence = {path = "./sentence"}

