/*
* TITLE  : NLP
* DESCRIPTION : NLP PACKAGE FOR MORE FASTER AND EFFICIENT ANALYSIS AND UNDERSTANDING OF TEXTS.
* AUTHOR : SUPRATIK CHATTERJEE
* YEAR OF CREATION   : 2019
* YEAR OF COMPLETION : ----
*
* MODULE : COMPRESSION
*
* MODULE DESCRIPTON
* Contains all compression logic.
*
* LICENSE : GNU AFFERO GENERAL PUBLIC LICENSE V3.0
*/


 
