/*
* TITLE  : NLP
* DESCRIPTION : NLP PACKAGE FOR MORE FASTER AND EFFICIENT ANALYSIS AND UNDERSTANDING OF TEXTS.
* AUTHOR : SUPRATIK CHATTERJEE
* YEAR OF CREATION   : 2019
* YEAR OF COMPLETION : ----
*
* MODULE : FILE
*
* MODULE DESCRIPTON
* File handlers, loaders, compressor decompressor, all exist within this module.
*
* LICENSE : GNU AFFERO GENERAL PUBLIC LICENSE V3.0
*/


